version: '3.4'

services:
  api:
    build: ./api/
    volumes: 
      - ./api/:/usr/src/app
    ports:
      - 8080:8080
    environment:
      PORT: 8080
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"