version: '3'

services:
  api:
    build: ./api
    volumes: 
      - ./api/:/usr/src/app
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    image: backend
  client:
    build: ./src
    ports:
      - "3000:80"
    image: frontend
